import { type Metadata } from "next";
import { Inter } from "next/font/google";
import { type PropsWithChildren } from "react";

import { JotaiProvider } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

const inter = Inter({
    subsets: ["latin"],
    display: "swap"
});

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <JotaiProvider>{children}</JotaiProvider>
            </body>
        </html>
    );
}
